TIPO_DOC_IDENTIDAD: dict[str, str] = {
    "0": "OTROS TIPOS DE DOCUMENTOS",
    "1": "DNI / DOCUMENTO NACIONAL DE IDENTIDAD",
    "4": "CARNET DE EXTRANJERIA",
    "6": "RUC / REGISTRO UNICO DE CONTRIBUYENTES",
    "7": "PASAPORTE",
    "A": "CEDULA DIPLOMATICA DE IDENTIDAD",
}

# Transcrito de las imágenes de source/CODIGOS DE TIPOS PARA CONTASIS.docx.
# La tabla salta de 46 a 48: el código 47 no existe.
TIPO_COMPROBANTE: dict[str, str] = {
    "00": "OTROS",
    "01": "FACTURA",
    "02": "RECIBO DE HONORARIOS",
    "03": "BOLETA DE VENTA",
    "04": "LIQUIDACION DE COMPRA",
    "05": "BOLETO TRANS. AEREO PASAJEROS",
    "06": "BOLETO TRANS. AEREO CARGA",
    "07": "NOTA DE CREDITO",
    "08": "NOTA DE DEBITO",
    "09": "GUIA DE REMISION - REMITENTE",
    "10": "RECIBO POR ARRENDAMIENTO",
    "11": "POLIZA BOLSA DE VAL, PRODU OTR",
    "12": "TICKET MAQUINA REGISTRADORA",
    "13": "DOCUMENTO ENTIDADES FINANCIERA",
    "14": "RECIBO SERV. PUBLICOS",
    "15": "BOLETO TRANSP PUBLIC URBANO",
    "16": "BOLETO DE VIAJE TRANSP PASAJER",
    "17": "DOCUM IGLESIA CATOLICA ARREND",
    "18": "DOCUMENTO EMITIDO POR AFPs",
    "19": "BOLETO EVENTOS PUBLICOS",
    "20": "COMPROBANTE DE RETENCION",
    "21": "CONOC EMBARQU TRANS CARGA MARI",
    "22": "COMPROB. OPER. NO HABITUALES",
    "23": "POLIZA ADJUD REMATE VENTA MART",
    "24": "CERTIF. PAGO REGALIA PERUPETRO",
    "25": "DOCUMENTO DE ATRIBUCION - IGV",
    "26": "RECIB. SERV AGUA FINES AGRARIO",
    "27": "SCTR - SEGUR COMPL TRAB RIESGO",
    "28": "TARIF UNIFICADA USO AEROPUERTO",
    "29": "DOCUM. EMITIDO POR COFOPRI",
    "30": "DOC EMPR ADQUI TARJ CRED DEBIT",
    "43": "BOL. AVIA COMER NO REGUL PASAJ",
    "44": "BILLET DE LOTERIA, RIFA Y APUE",
    "45": "DOC EMIT CENT EDUC NO GRAVADOS",
    "46": "FORMULARIO DE DECLARACION VI",
    "48": "COMPROBANTE DE OPERACIONES - LEY N 29972",
    "49": "CONSTANCIA DE DEPOSITO - IVAP",
    "50": "DECLARACION UNICA ADUANAS - ID",
    "51": "POLIZA O DUI FRACCIONADA",
    "52": "DESPACHO SIMPLIF. - IMPOR SIMP",
    "53": "DECLARACION MENSAJERIA COURIER",
    "54": "LIQUIDACION DE COBRANZA",
    "55": "BVME TRANS FERROV PASAJEROS",
    "56": "COMPROBANTE PAGO SEAE",
    "87": "NOTA DE CREDITO ESPECIAL",
    "88": "NOTA DE DEBITO ESPECIAL",
    "89": "NOTA DE AJUSTE DE OPERACIONES - LEY N 29972",
    "91": "COMPROBANTE DE NO DOMICILIADO",
    "96": "EXCESO CRED FISC x RETIRO BIEN",
    "97": "NOTA CREDITO - NO DOMICILIADO",
    "98": "NOTA DEBITO - NO DOMICILIADO",
    "CH": "CHEQUE",
    "DP": "DEPOSITO",
    "LA": "LIBRO DE ACTAS",
    "LE": "LETRA DE CAMBIO",
    "LI": "LIQUIDACION",
}

TIPOS_NOTA_CREDITO = frozenset({"07", "87", "97"})
TIPOS_NOTA_DEBITO = frozenset({"08", "88", "98"})

# Documento de identidad genérico usado en boletas al público. Contasis escribe
# "1 / 11111111"; la descarga del SIRE trae "-" en ambos campos.
DOC_IDENTIDAD_GENERICO = "11111111"


def describe_comprobante(tipo_cp: str) -> str:
    return TIPO_COMPROBANTE.get(tipo_cp, f"DESCONOCIDO ({tipo_cp})")


def describe_doc_identidad(tipo_doc: str) -> str:
    return TIPO_DOC_IDENTIDAD.get(tipo_doc, f"DESCONOCIDO ({tipo_doc})")


def es_nota(tipo_cp: str) -> bool:
    return tipo_cp in TIPOS_NOTA_CREDITO or tipo_cp in TIPOS_NOTA_DEBITO
