/** Tipos que admite la clasificación y revisión de la API de captura. */
export const tiposDocumento = [
  { valor: 'FACTURA', texto: 'Factura' },
  { valor: 'HONORARIOS', texto: 'Recibo por honorarios' },
  { valor: 'BOLETA', texto: 'Boleta de venta' },
  { valor: 'NOTA_CREDITO', texto: 'Nota de crédito' },
  { valor: 'NOTA_DEBITO', texto: 'Nota de débito' },
  { valor: 'GUIA_REMITENTE', texto: 'Guía de remisión remitente' },
  { valor: '10', texto: '10 · Recibo por arrendamiento' },
  { valor: '13', texto: '13 · Documento autorizado SBS' },
  { valor: 'SERVICIO_PUBLICO', texto: 'Servicio público' },
  { valor: '18', texto: '18 · Aporte AFP' },
  { valor: '19', texto: '19 · Boleto de espectáculo' },
  { valor: '22', texto: '22 · Operaciones no habituales' },
  { valor: '23', texto: '23 · Póliza de adjudicación' },
  { valor: '25', texto: '25 · Documento de atribución' },
  { valor: '26', texto: '26 · Agua con fines agrarios' },
  { valor: '29', texto: '29 · COFOPRI' },
  { valor: '30', texto: '30 · Documento adquirente de tarjetas' },
  { valor: 'GUIA_TRANSPORTISTA', texto: 'Guía de remisión transportista' },
  { valor: '34', texto: '34 · Documento del operador' },
  { valor: '35', texto: '35 · Documento del partícipe' },
  { valor: '36', texto: '36 · Recibo de distribución de gas natural' },
  { valor: '42', texto: '42 · Documento de tarjetas propias' },
  { valor: '53', texto: '53 · Declaración de mensajería courier' },
  { valor: '64', texto: '64 · Servicios relacionados con transporte aéreo' },
  { valor: '87', texto: '87 · Nota de crédito especial' },
  { valor: '88', texto: '88 · Nota de débito especial' },
  { valor: '91', texto: '91 · Comprobante no domiciliado' },
  { valor: '96', texto: '96 · Exceso de crédito fiscal por retiro' },
  { valor: '97', texto: '97 · Nota de crédito no domiciliado' },
  { valor: '98', texto: '98 · Nota de débito no domiciliado' },
  { valor: 'YAPE_TRANSFER', texto: 'Transferencia Yape' },
  { valor: 'YAPE_SERVICE_PAYMENT', texto: 'Pago de servicio Yape' },
  { valor: 'PLIN_TRANSFER', texto: 'Transferencia Plin' },
  { valor: 'BANK_TRANSFER', texto: 'Transferencia bancaria' },
  { valor: 'POS_VOUCHER', texto: 'Voucher POS' },
  { valor: 'CASH_DEPOSIT', texto: 'Depósito en efectivo' },
  { valor: 'DAILY_SETTLEMENT', texto: 'Liquidación diaria' },
  { valor: 'OTHER_DOCUMENT', texto: 'Otro documento' },
  { valor: 'UNKNOWN', texto: 'Sin clasificar' },
];
